services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  postgres-wallet:
    image: postgres:15
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  postgres-balances:
    image: postgres:15
    environment:
      POSTGRES_DB: balances_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  wallet-core:
    build: ./wallet-core
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-wallet:5432/wallet_db
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: wallet.balance.updated
      WALLET_SERVICE_PORT: 3002
    depends_on:
      - kafka
      - postgres-wallet
    ports:
      - "3002:3002"

  balances:
    build: ./balances
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-balances:5432/balances_db
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: wallet.balance.updated
      PORT: 3003
    depends_on:
      - kafka
      - postgres-balances
    ports:
      - "3003:3003"
